spring:
  application:
    name: gambling-detection-api
  
  # H2 Database - Zero configuração necessária!
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  # H2 Console - Para visualizar o banco
  h2:
    console:
      enabled: true
      path: /h2-console
    
  jpa:
    hibernate:
      ddl-auto: create-drop  # Cria e recria as tabelas automaticamente
    show-sql: true  # Mostra as queries SQL no console
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
      
server:
  port: 8080
  
# Logs simplificados
logging:
  level:
    br.com.gambling: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss} - %msg%n"
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  info:
    title: Gambling Detection API
    description: API para detecção e prevenção de apostas compulsivas
    version: 1.0.0
    contact:
      name: Equipe de Desenvolvimento
      email: dev@gambling-detection.com
    license:
      name: MIT License
      url: https://opensource.org/licenses/MIT
